name: build

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: FetchSourceCode
        uses: actions/checkout@v3

      - name: SecretScan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true
        continue-on-error: true
